Delete run scripts

diff --git a/Test_Run/dockerfile b/Test_Run/dockerfile
--- a/Test_Run/dockerfile
+++ b/Test_Run/dockerfile
@@ -10,8 +10,11 @@ RUN pip install --no-cache-dir -r requirements.txt
 
 EXPOSE 8501
 
+RUN echo "Listing /app contents:" && ls -la /app && \
+    echo "Showing run_scripts.sh content:" && cat /app/run_scripts.sh || echo "File not found"
+
 RUN ls -la /app
 
-RUN chmod +x run_scripts.sh
+RUN chmod +x /app/run_scripts.sh
 
 ENTRYPOINT ["/app/run_scripts.sh"]
